### ISSUE TITLE
[Task] Uruchomienie środowiska uruchomieniowego OCI

### ISSUE THREAD

**Issue by msz13** [msz13/zapisywarka#88]
# Desription

# Tasks
- [ ] Kubernetes na pojedynczej maszynie
- [ ] HA cluster
- [ ] Networking
- [ ] Volumes 
- [ ] Postgresql
- [ ] Backup object storage

**Comment by msz13** [comment]
#### Propozycja architektury HA

1. Każdy control plane node w osobnej avability zone
2. Public subnet for control plane
3. kubernetes load balancer do decyzji - oci albo metallb albo z k3s

#### Zabezpieczenie nodeów
  * dezaktowaoc roota
  * tylko user z ssh moze sie logowac
  * zmienic port ssh na inny niz 22
  * firewal rules
    * zezwól na połaczenia wychodzące
    * na przychodzące tylko, z load balanser, albo 80 i 443, ssh, komunikacja miedzy kubernetes

**Comment by msz13** [comment]
### Konfiguracja DNS
dostępne dla administratora z adresu kube.admin.zapisywarka.pl
monitoring grafana.admin.zapisywarka.pl
baza danych postgres.admin.zapisywarka.pl

dwie trasy:
1. kube.admin.zapisywarka.pl przekierowany jest do kube admin
2. reszta zapytan przekierowana jest do kubernetes ingress controller

opcje:
- czy kube api jest pod publiczna domena, czy oracle

**Comment by msz13** [comment]
do zrobienia 

- [ ] uruchomienie serwera po domenie z terraform, publikacja aplikacji

**Comment by msz13** [comment]
repositories:
  - name: stackgres-charts
    url: https://stackgres.io/downloads/stackgres-k8s/stackgres/helm/
  - name: bitnami
    url: https://charts.bitnami.com/bitnami
  - name: jetstack
    url: https://charts.jetstack.io


releases:
  - name: stackgres-operator
    chart: stackgres-charts/stackgres-operator 
  - name: postgresql-cluster  

  - name: zapisywarka-api
  - name: zapisywarka-rejestracja


environments:
  dev:

**Comment by msz13** [comment]
---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: {{ .Values.issuerName }}
  spec:
    acme:
       # The ACME server URL
      server: {{ .Values.server }}
       # Email address used for ACME registration
      email: {{ .Values.email }}
       # Name of a secret used to store the ACME account private key
      privateKeySecretRef:
        name: {{ .Values.issuerSecret }}
       # Enable the HTTP-01 challenge provider
      solvers:
        - http01:
            ingress:
              class: {{ .Values.ingressClass }}
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: acme-crt
spec:
  secretName: {{ .Values.certyficateSecret }}
  dnsNames:
{{ .Values.hostNames | toYaml | indent 3 }}
  issuerRef:
    name: {{ .Values.issuerName }}
    # We can reference ClusterIssuers by changing the kind here.
    # The default value is Issuer (i.e. a locally namespaced Issuer)
    kind: ClusterIssuer
    group: cert-manager.io

**Comment by msz13** [comment]
[Uploading environemnts.docx…]()

**Comment by msz13** [comment]
[environemnts.docx](https://github.com/msz13/zapisywarka/files/10203351/environemnts.docx)

**Comment by msz13** [comment]
oracle container engine
- założyć poprzez quick start i konsole
- założyć prosty claster przez terraform, albo moduł, albo własne definicje

**Comment by msz13** [comment]
```
---
{{- define "webservice.imagePullSecrets" -}}
{{- $pullSecrets := .Values.global.imagePullSecrets | default .Values.imagePullSecrets -}}
{{- if $pullSecrets -}}
imagePullSecrets: 
  - name: {{ $pullSecrets }}  
{{ end }}
{{- end }}

example: 
{{- include "webservice.imagePullSecrets" . | nindent 0 -}}
containers:

```

**Comment by msz13** [comment]
https://helm-playground.com/#t=N7C0AIBMFMDMEsB21wCIAuBDAzgawHSKYC20q4oAvpQFAjgAOATkurGgKTahfn4DCAC0xN0%2BAHIkU%2BAErQANtBzQJU8LIVLsKuQDd42eAHtE4anTDhoiSBXOgHNTA3gA1aE0MmAXOABGmOgAxoIA9LoAjDS4SJC%2BAFJGfjSkWJCBmN404OBEpL70SEHyAK4waFh4hFJ8ZrQ5mIiIRljoxojYvtk54DTYDNBBWTno0MQM8oHQwz39gzM94EEmWEgend2LEHnT4PQCwqKqpHWbi%2BDwxJgA5rsDTPLeAKz4AMwALPgADGeLy8RXGwFYDqVyYUrQbD4f6A2zmc49ETXTp7EH4MEQqFI7CnBFMSFYUQABSM8ngQQAnr5xNBdB5ugEgrgjLBYAAZS7wdC%2Bd40IA&v=LQhQGIBcEMGcGsA0ACAVgewEalAOgMIAW0ATpLgHLQC2ApgFzIAqc8OoAltdAOYOjJkJWjw6xIJAJ6MARDIFDaAB3SwOkdFNnzBMHttABjdNW4A7ACaMA2hfSQztSChIBXM7gsAbALqhSPLA2foTo6PCMSsIcZuLQXl4oUbSuSjwk0Ba0oKHhAOq0HDyEkIzAAIwADJX%2BhpAcAG60ACK0mV4xtADKtMaWQchVlUA

**Comment by msz13** [comment]
- poprawić image pull secrets
- dodać steps do db-migrations do ci/cd
- dodac cert manager

**Comment by msz13** [comment]
local workflow

- build image
- tag
- deploy witth: set $appname.image.tag $tag

ci/cd worflow
local workflow

- build image
- tag
- update manifests yq $appname.image.tag: $tag
- deploy witth:

**Comment by msz13** [comment]
Components
•	app
o	Webservice
o	Task
o	imagePullSecret
•	Infrastructure
o	Cert issuer
o	Imagepull secrets

extraDeploy: |
  apiVersion: bitnami.com/v1alpha1
  kind: SealedSecret
  metadata:
    name: mysecret
    namespace: mynamespace
    annotations:
      "kubectl.kubernetes.io/last-applied-configuration": ....
  spec:
    encryptedData:
      .dockerconfigjson: AgBy3i4OJSWK+PiTySYZZA9rO43cGDEq.....
    template:
      type: kubernetes.io/dockerconfigjson
      # this is an example of labels and annotations that will be added to the output secret
      metadata:
        labels:
          "jenkins.io/credentials-type": usernamePassword
        annotations:
          "jenkins.io/credentials-description": credentials from Kubernetes

**Comment by msz13** [comment]
How to add single resource to app:
•	extra deploy
•	template z secretem i values
•	chart referencing sub chart z dodanymi pełnymi resourcami w template
•	flux cd
o	kustomisation
	release
	namespace
	selad secret – dockerconfigjson
kubectl apply namespace dokcer config json
helm release

**Comment by msz13** [comment]
export PROJECT=test1
export ${PROJECT}_IMAGE="TESTVALUE"
echo $test1_IMAGE

**Comment by msz13** [comment]
Do zrobienia:
- albo uruchamianie app i testow z serve  i start db (wtedy trzeba podac inny adres do testow)
- uruchamianie w kubernetesie - trzeba uzyc skrypt na start local k3d i uruchamiac z helm
- uruchamiac po prostu z docker

**Comment by msz13** [comment]
Server Site MVC
Dotnet-Apa – serverd in dotnet
SPA, back, served separatley
baza danych

Środowisko deweloperskie
Docker + docker database

Run script (run database, migrate, serve)
Docker compose (run database, migrate, run docker)
Manage by test test containers


Środowisko staging
- APP insights
- Fly.io
- App containers/App instances
- Kubernetes


Deploying front
Deploying backend
Deoploung data base schema
